Service calls
zxdavb/evohome_cc pull request #10
Opened 2021-02-20 10:31 UTC by phdelodder

2021-02-22 06:43 UTC, phdelodder commented
Currently has one know issue for me is that the until being set by evohome_rf is completely ignored by the controller, resulting in ignoring the complete setpoint request

2021-02-28 13:25 UTC, iMiMx commented
Seems to work pretty well for me so far, many thanks - this is'was the main aspect I'm still relying on the internet gateway for, the ability to set a time based override using (evohome_cc.clear_zone_override).

I did notice that the example data seems to be missing, so when you click 'FILL EXAMPLE DATA' on the Developer Tools Services, it doesn't automatically populate defaults for easy testing as the other evohome.* service calls do.

2021-03-01 06:52 UTC, phdelodder commented
@iMiMx I have update the services.yaml to be able to use the auto populate the fields with the example button. 

For the setpoint status, I don't know if the info is already available through evohome_rf.

2021-03-08 07:09 UTC, iMiMx commented
I think, service_calls might be broken with the merged latest release - for example the below does not set an override:

```
service: evohome_cc.set_zone_override
data:
  entity_id: climate.office_2
  setpoint: 5
  duration:
    minutes: 135
```

I don't have much/any logging enabled by default, will perform some more tests later.

2021-03-08 07:19 UTC, phdelodder commented
@iMiMx commit 35a8951 should fix it!

2021-03-08 11:31 UTC, iMiMx commented
Is/was there some 'force refresh after change' that might also be missing/broken with recent changes?  I see some commits above for this.

On the earlier 0.5.10 commits the UI seemed to update reasonably quickly, on the latest versions when you set an override using your service_calls (or simply manually make a change to 'temporary' via the UI), it takes some time to update.  With the manual present change, it flicks 'temporary', then back to 'None', before it then changes back to 'Temporary'.

2021-03-08 12:03 UTC, phdelodder commented
The refresh(using self._refresh()) still remains the same, it hasn't changed since the previous code. I guess first needs to get this merge so it's being tested by more people

2021-03-11 23:45 UTC, zxdavb requested changes
Can you rebase please?

2021-03-12 20:34 UTC, zxdavb reviewed
Here's a start - you have a few of these:
```
temp_modes = [m for m in SYSTEM_MODE_LOOKUP if m == EVO_MODE_ECO]
```
 - they make sense for **evohome**, but not here - they need to go.

2021-03-12 20:34 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +    temp_modes = [m for m in SYSTEM_MODE_LOOKUP if m == EVO_MODE_AWAY or m == EVO_MODE_CUSTOM or m == EVO_MODE_DAY_OFF]
Why not:
```
temp_modes = [m for m in SYSTEM_MODE_LOOKUP if m in (EVO_MODE_AWAY, EVO_MODE_CUSTOM, EVO_MODE_DAY_OFF)]
```
or better:
```
temp_modes = (EVO_MODE_AWAY, EVO_MODE_CUSTOM, EVO_MODE_DAY_OFF)
```
... or - as it appears to be a constant;
```
TEMP_MODES = (EVO_MODE_AWAY, EVO_MODE_CUSTOM, EVO_MODE_DAY_OFF)
```

2021-03-12 20:34 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +    if temp_modes:  # any of: EVO_MODE_AWAY, EVO_MODE_CUSTOM, EVO_MODE_DAY_OFF, permanent or for 1-99 days
If using `TEMP_MODES = ` (i.e. it's a constant), then the `if TEMP_MODES:` isn't needed at all?

2021-03-12 20:34 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +                vol.Required(ATTR_SYSTEM_MODE): vol.In(temp_modes),
```
vol.Required(ATTR_SYSTEM_MODE): vol.In(TEMP_MODES),
```

2021-03-12 20:34 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +    if [m for m in SYSTEM_MODE_LOOKUP if m == EVO_MODE_RESET]:
I think you've copied this from the **evohome** integration without understanding the nuances?

2021-03-12 20:34 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +from .const import EVO_MODE_AWAY, EVO_MODE_CUSTOM, EVO_MODE_ECO, EVO_MODE_DAY_OFF, EVO_MODE_RESET, EVO_MODE_AUTO, EVO_MODE_HEAT_OFF
These `const`s should come from **evohome_cc.const** _or_ **evohome_rf.const**, but not both, see above.

2021-03-12 20:34 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +    SYSTEM_MODE_LOOKUP
These consts should come from **evohome_cc.const** or **evohome_rf.const**, but not both, see below.

2021-03-12 20:35 UTC, zxdavb commented on custom_components/evohome_cc/__init__.py
> +    SYSTEM_MODE_LOOKUP
I think I'll refactor to come from **evohome_rf**.

2021-03-13 20:09 UTC, zxdavb commented
All this is in 0.6.5 - so, close

2021-03-13 20:09 UTC, closed without merging